### ISSUE TITLE
Make multiple pass optional

### ISSUE THREAD

**Issue by wes-r** [pshihn/rough-notation#10]
Right now many of the annotations use two passes (i.e. underlines things twice). I suggest removing this default and instead add a `reverse` option. That way people can completely control how many passes they want and maybe a delay between them:

```js
const a1 = annotate(document.querySelector('#e1'), { type: 'underline' });
const a2 = annotate(document.querySelector('#e1'), { type: 'underline', reverse: true });

const ag = annotationGroup([a1, /*way_to_add_delay?*/, a2]);
ag.show();
```

**Comment by pshihn** [comment]
I like the idea of controlling one pass vs second pass. 
I'm not sure what the use case for the delay between the two passes would be.
