### ISSUE TITLE
Underline annotation renders incorrectly on small screens like iPhone 5/SE

### ISSUE THREAD

**Issue by pbamotra** [pshihn/rough-notation#11]

**Comment by pshihn** [comment]
What version of safari are you running? Perhaps share a screenshot? 
Thanks!

**Comment by lucasverra** [comment]
It seems good to me, I just tested it
![image](https://user-images.githubusercontent.com/11323803/83260283-ca1ad800-a1b9-11ea-9738-407c924dc07a.png)

**Comment by pbamotra** [comment]
![image](https://user-images.githubusercontent.com/6505165/83276868-18ae7f00-a186-11ea-8cbe-b30e05e260d7.png)

I changed the word on your website to "Computer vision" and also the circle in the bottom you can see. I tested it on Brave browser using the devtools.

**Comment by fspoettel** [comment]
@pbamotra The plugin picks up changes to the viewport size via [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) and renders again in that case.

It cannot detect changes to the DOM made by inline HTML edits, hot reloading environments and changes via DOM attributes such as `.textContent`. In that case the annotation will not be redrawn automatically. You could trigger a redraw programatically via the `.show()/.hide()` methods.
