### ISSUE TITLE
[Feature]: Change color or strokeWidth after annotate

### ISSUE THREAD

**Issue by linkstrifer** [pshihn/rough-notation#16]
Is there a way to change the annotation properties after annotate?

I didn't find the way to do it and checking at the code doesn't look like is there one but maybe I'm wrong

Use case:
- Annotate content (`annotation.show()`)
- Change the color line after render for contrast, like when you change between dark-theme and light-theme

Right now I have to re-annotate, losing the svg a drawing a new one

**Comment by pshihn** [comment]
Thats a good feature request - for all config properties. 
We just need to make sure which ones will cause a re-render and which don't. Padding, for example should cause a re-render.

**Comment by pshihn** [comment]
This is now supported with https://github.com/pshihn/rough-notation/pull/31
