### ISSUE TITLE
Request: Distinct X and Y (or top/right/bottom/left) padding values

### ISSUE THREAD

**Issue by rococode** [pshihn/rough-notation#25]
I think it would be great if padding could be more fine-grained to allow more complete control over the visuals. For example, right now if you have a `box` annotation on two lines of text, the boxes may awkwardly overlap. This could be resolved by using negative top/bottom padding to give them some breathing room. 

For example, with 0 padding on all annotations:

![](https://i.imgur.com/qqRMB26.png)

With -3 padding on the box, the top border looks (imo) nicer:
![](https://i.imgur.com/ZHs7ory.png)

But obviously, since padding is currently applied uniformly and thus the other sides of the box also get -3 padding, it's not really usable.

Some quick thoughts on a possible implementation that wouldn't change the API too much:

`padding` in `RoughAnnotationConfig` has type `number` (love that this is Typescript, by the way!), it could be changed to be typed `number | [number, number] | [number, number, number, number]`. 

Then `renderAnnotation` would have a bit of extra logic to check which variant of the padding definition it is and use it accordingly. 

So `[number, number]` would apply to X and Y respectively, `[number, number, number, number]` would apply to top/right/down/left like in CSS. For things like box where the actual rendering draws a full rectangle, it would just be a tiny bit of extra math to get the padding right.

**Comment by pshihn** [comment]
Good idea. should be easy to implement.

**Comment by pshihn** [comment]
Implemented in #26
