### ISSUE TITLE
Is it possible to .show() a second time, but with no animation?

### ISSUE THREAD

**Issue by dimavolo** [pshihn/rough-notation#27]
Amazing work on this library!

I'm trying to add annotations to elements that end up shifting in their container after they have been annotated. The result is the annotation stays put, but the element has moved, so the element and its annotation no longer match up.

My solution is to call `.show()` again to repaint, but the annotations all animate again.

Is it possible to call `.show()` a second time, but without animation?

Or is there a better approach overall to solving for this problem of elements moving over in their container after the annotation has already been painted?

Thanks again!

**Comment by dimavolo** [comment]
Update: I suspect it might be `annotation._config.animate = false`

One side-effect of my overall approach is calling `.show()` a second time makes all the annotation on the screen repaint in slightly different strokes (since they're appear hand-drawn). It's noticeable and a bit jarring to the user when this happens.

**Comment by pshihn** [comment]
Coincidentally, I was working on this same problem in a branch. Will have a solution later today. As to maintaining the same strokes, I will address that separately.

**Comment by dimavolo** [comment]
Awesome @pshihn, thanks for the quick reply!

**Comment by pshihn** [comment]
Addressed by https://github.com/pshihn/rough-notation/pull/31
