### ISSUE TITLE
Feature request: add class name to svg

### ISSUE THREAD

**Issue by zoffixznet** [pshihn/rough-notation#28]
It would be extremely helpful to add some sort of a classname to the generated `<svg>` element (optionally, could be configurable).

The usecase I have is Bootstrap's input groups have `z-index` applied and so they show up on top of the drawn annotation. Applying an even higher `z-index` to `svg` works, but in this case also affects `<svg>` icons inside the button and also breaks `highlight` annotation type.

A class on the annotated `<svg>` would let users easily apply any CSS properties they might require.

**Comment by pshihn** [comment]
good idea. I will give it a unique class name. I think that would be simpler than letting the user configure the class name
