### ISSUE TITLE
Generation of Invalid Markup (e.g. when annotating <td>s)

### ISSUE THREAD

**Issue by zoffixznet** [pshihn/rough-notation#29]
Don't know if this would be considered a bug or documentation improvement. I added a bunch of annotation to `<td>` elements, and that caused `<svg>` elements to be inserted alongside those `<td>`s which blew up my tables and I think is also an invalid markup.

In some table setups it might be hard to figure out where the td shift is coming from.

**Comment by pshihn** [comment]
You're right tables are unique because they do not work with standard layout.
