### ISSUE TITLE
Broken in WebView (twitter on android)

### ISSUE THREAD

**Issue by pshihn** [pshihn/rough-notation#3]
See https://twitter.com/KrComet/status/1265683331041001474?s=20

**Comment by mbifulco** [comment]
Seems to have a similar issue on wider viewports, too - this is Chrome-Edge on windows on a 4k desktop:

![image](https://user-images.githubusercontent.com/1844496/83054996-3ca48000-a021-11ea-969e-db75d25e052d.png)

**Comment by pshihn** [comment]
could be related to the device pixel ratio perhaps

**Comment by pshihn** [comment]
@mbifulco  does this happen when you resize or when you initially load?

**Comment by mbifulco** [comment]
@pshihn after some testing, it seems to be specific to the monitor I'm viewing it on.  My 4k screen shows things offset as above, regardless of width.  When I move the browser to the native monitor on my machine (a Surface Book), everything looks great.  

Maybe a pixel density thing?

**Comment by pshihn** [comment]
could be. 

Seems like it may be broken on Chrome on Windows as well with a certain pixel density

**Comment by hunj** [comment]
Chrome on Windows 10 with 4k monitor here. The issue seems to be from Window's resolution scaling. I was able to see it behave correctly when I followed the steps below:

1. Right click on desktop -> Display Settings 
2. Under **"Scale and layout"**, set **Change the size of text, apps, and other items**'s value to `100%`.

![image](https://user-images.githubusercontent.com/3972717/83066975-dffe9080-a033-11ea-8688-1d977344a908.png)

_(hope you like the "rough notation" in the screenshot 😄)_

**Comment by baldurbjarnason** [comment]
You can also replicate this bug (at least, I think it's the same bug) by using the text zoom feature on Chrome desktop on every OS, I think. But using text zoom on Firefox and Safari is fine.

Positioning seems to return to normal if you go into the web inspector and remove the 1px height and width properties on the svg.

**Comment by pshihn** [comment]
1px width/height was needed to render on Chrome on Mac. Some sort of browser optimization.

**Comment by Qix-** [comment]
Resetting my zoom in Chrome to 100% fixes this issue. Changing zoom to anything other than 100% causes all of the positioning issues.

**Comment by pshihn** [comment]
Alright, I think I have fixed this issue. 
Can you try https://roughnotation.com/ now and see if it all is working (page may be cached)

**Comment by baldurbjarnason** [comment]
Seems to work now 👍  Changing the zoom level no longer breaks positioning in any of my Chromes (tested on ChromeOS, macOS, and Windows). :-)

**Comment by Qix-** [comment]
@pshihn Yep, confirmed works. Nice one :)

**Comment by pshihn** [comment]
Seems like it's fixed in v0.1.1
