### ISSUE TITLE
Underline loads on incorrect location, adjusts to a correct one on scroll

### ISSUE THREAD

**Issue by honzajavorek** [pshihn/rough-notation#63]
The issue is currently visible live [here](https://junior.guru/club/), but in case I change the live page, this is a video report from my visitor:

https://user-images.githubusercontent.com/283441/127834454-3277c412-9306-4e25-afb6-1d4b5286d8af.mp4

I experience the same thing and get reports from other users on different browsers and OSes (Firefox, Chrome, macOS, Windows, with fonts, with web fonts disabled…), so I don't think it's specific to a certain browser. My code:

```html
<script defer src="bundle.js"></script>
...
<header class="masthead">
  <div class="masthead-container">
    <div class="masthead-content">
      <h1>Tvoje programovací parta</h1>
      <div class="lead">
        <p>
          Začátečníci, kteří to myslí vážně. Profesionálové s chutí pomáhat.
          V klubu svoje programování nebo hledání práce posuneš o <strong>1 % každý den</strong>.
        </p>
      </div>
      <div class="masthead-numbers">...</div>
      <a class="masthead-button primary" href="#cenik">Přidej se</a>
      <span class="masthead-members">...</span>
    </div>
    <img class="masthead-illustration" src="../static/images/illustration-club.svg">
  </div>
</header>
```

```js
import { annotate } from 'rough-notation';

document.addEventListener('DOMContentLoaded', function () {
  Array.from(document.querySelectorAll('.masthead .lead strong'))
    .forEach(function (element) {
      const annotation = annotate(element, {
        type: 'underline',
        color: '#1755d1',
        animationDuration: 1600,
      });
      annotation.show();
    })
});
```

The underline seems to find wrong position, often alongside the top of the element instead of its bottom. The issue is intermittent. Sometimes it loads correctly. Reload of the page sometimes help. Sometimes it does not. Often the location adjusts on scroll or window resize, but sometimes it does not.

I thought it could be something with `defer` and `DOMContentLoaded`, but playing around with those has no effect. Any clues why this could be happening? Easy solution would be not to use Rough Notation, but I like it a lot, I use my own stupid cartoons as illustrations, so it matches the visual style of the page.

**Comment by pshihn** [comment]
This is likely due to some delayed CSS or web font loading. When RoughAnnotation computes the size vs when the CSS/font loads. This is just a guess. I'll investigate properly later today and get back to you.

**Comment by honzajavorek** [comment]
Thank you! There should be no web fonts. There's Bootstrap on the page and I'm using whatever they default to. Although, there's [Bootstrap Icons](https://icons.getbootstrap.com/) on the page, which is implemented as a font 🤔

**Comment by honzajavorek** [comment]
Ha! I probably managed to debug it after all. There is an `<img>` tag (the illustration on the right), where I forgot to add `width` and `height` attributes right in the HTML, to fix a default size before the CSS loads. This has been causing shifts after loading, which are probably causing the Rough Notation's underline to jump around. Thanks for your comment @pshihn as it helped me to look for the right clues! ❤️
