### ISSUE TITLE
Question: Usage of Selectors

### ISSUE THREAD

**Issue by philippsta** [pshihn/rough-notation#65]
First of all: Thank you for this amazing library! 

I am new to javascript and got it running with the help of some friends. 
However I do have some questions and hope you can help me out: 

1. How can I use the same selector multiple times? 
I created a selector .ul-pink and want to use it multiple times within the same page: https://codepen.io/philippstakenborg/pen/gOGNdWj 
Problem: It only shows the first selector, not the second. Can I change that? 

2. What to do when a defined selector is not used in HTML? 
When all my selectors (.ul-pink / .ul-green / .ul-yellow) are used, it works. 
https://codepen.io/philippstakenborg/pen/VwMJBpv

Problem: When I delete one selector in HTML (.ul-yellow), nothing works. 
https://codepen.io/philippstakenborg/pen/BawgPRd 

Sorry for my bad formulations, I am new to this and hope you guys can help me out. 

Greetings,
Philipp

**Comment by philippsta** [comment]
A friend helped me answering the second question: The solution are If-Requests! 
https://codepen.io/philippstakenborg/pen/ZEXdMvb

**Comment by Alexs7zzh** [comment]
https://codepen.io/alexs7zzh/pen/ZEXdwQe

**Comment by philippsta** [comment]
Thank you Alex! This works perfectly!
