### ISSUE TITLE
I hope to support Vitepress or Astro.

### ISSUE THREAD

**Issue by bd-dxg** [pshihn/rough-notation#79]
Hello developer!

The animations in this library are really cool, I really like it. Currently, I have built my own blog using vitepress, but you know, the article format is all in markdown, so it's difficult to utilize this library to add effects to the articles.

I hope in the future, this library can be supported as a plugin for vitepress or Astro.

Thank you very much for your development!

**Comment by TBG-FR** [comment]
I currently use that plugin with an Astro website without any issue. I did it only on HTML pages, but I just tried it on a Markdown page and it worked quite well (however you have to add some `<span>` in your markdown)

`test.md`
```mdx
---
title: 'RoughNotation Test'
author: 'TBG-FR'
date: '03/11/2023'
---

# Title

## Subtitle

### Section

Here is some text. <span id='testH'>This part should be highlighted</span>. <span id='testU'>And this part should be underlined</span>. However, this part isn't styled at all.

<script type='module'>
    import { annotate } from 'https://unpkg.com/rough-notation?module';

    const h = document.querySelector('#testH');
    const hAnnotation = annotate(h, { type: 'highlight', color: 'yellow' });
    hAnnotation.show();

    const u = document.querySelector('#testU');
    const uAnnotation = annotate(u, { type: 'underline', color: 'red' });
    uAnnotation.show();
</script>
```

`test.astro`
```astro
---
import * as test from '../pages/content/test.md';
---
<html>
    <head>
        <title>{test.frontmatter.title}</title>
    </head>
    <body>
        <test.Content />
    </body>
</html>
```

Result
![image](https://github.com/rough-stuff/rough-notation/assets/18146038/0b545885-5106-4fd4-b10a-f9ea88a7d77a)

**Comment by bd-dxg** [comment]
thank you for your reply
